[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  GOOGLE_SHEETS_PRODUCT_URL = "https://script.google.com/macros/s/AKfycbwj57zDGnWB4H3_x6ghLsLdyYcyB-aGLUxWXcUo5pzwXMwJ5QkbGHIWz3SP5V5DBCSJ/exec"

[[plugins]]
  package = "@netlify/plugin-nextjs"
