const productsRaw = [
    {
        handle: "integrated-homes-1-5kva-solar-inverter",
        title: "Integrated Homes Gadget Pack: 1.5kva 12v Solar Inverter",
        body: "<p>This essential solar power pack includes a 1.5kVA 12V inverter, designed to keep your lights, fans, phones, and laptops running during power outages. It's the perfect entry-level solution for reliable, clean energy for your home.</p>",
        price: 789000,
        image: "https://i.postimg.cc/QdTMzQvh/5kva_setup.jpg",
        status: "active",
        seoTitle: "Integrated Homes 1.5kVA Solar Inverter Pack Price in Nigeria | Linos Security",
        seoDesc: "Buy the Integrated Homes 1.5kVA 12V Solar Inverter Pack in Nigeria. Perfect for essential appliances like lights and fans. Durable, efficient, with expert installation. Order now!",
        category: "Solar Power",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Integrated%20Homes%201.5kva%20Solar%20Inverter%20Pack"
    },
    {
        handle: "family-power-2-5kva-solar-inverter",
        title: "Family Power Security Pack: 2.5kva 12v Solar Inverter",
        body: "<p>Power more of your home with this 2.5kVA 12V solar inverter system. Ideal for running multiple lights, fans, TVs, and decoders simultaneously. A robust solution for family comfort during load shedding.</p>",
        price: 980000,
        image: "https://i.postimg.cc/QdTMzQvh/5kva_setup.jpg",
        status: "active",
        seoTitle: "Family Power 2.5kVA Solar Inverter Price in Nigeria | Linos Security",
        seoDesc: "Upgrade to the Family Power Security Pack 2.5kVA 12V Solar Inverter in Nigeria. Run TVs, fans, and lights seamlessly. Get a durable system with professional installation.",
        category: "Solar Power",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Family%20Power%202.5kva%20Solar%20Inverter%20Pack"
    },
    {
        handle: "essential-3-5kva-48v-hybrid-inverter",
        title: "Essential Premium Power packs 3.5kva 48v Hybrid",
        body: "<p>Experience next-level efficiency with this 3.5kVA 48V Hybrid Solar Inverter. It intelligently manages solar power, battery, and grid to power heavy loads like fridges and freezers, ensuring maximum energy savings.</p>",
        price: 1320000,
        image: "https://i.postimg.cc/D0BZZqRk/family_solarpanel_scaled.jpg",
        status: "active",
        seoTitle: "3.5kVA 48V Hybrid Solar Inverter Price Nigeria | Linos Security",
        seoDesc: "Buy the 3.5kVA 48V Hybrid Solar Inverter in Nigeria. Ideal for powering fridges, freezers, and TVs with intelligent energy management. Durable and efficient. Order today!",
        category: "Solar Power",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Essential%20Premium%203.5kva%20Hybrid%20Solar%20Inverter"
    },
    {
        handle: "super-home-5kva-48v-hybrid-inverter",
        title: "SUPER HOME PREMIUM PACK 5kva 48v Hybrid Solar Inverter",
        body: "<p>The ultimate home solution. This 5kVA 48V Hybrid system powers multiple heavy appliances including inverter ACs, water pumps, and kitchen electronics. Enjoy whole-home comfort, even without the grid.</p>",
        price: 4439500,
        image: "https://i.postimg.cc/Jz69jvpM/1-5KWzhutu2-800-800.jpg",
        status: "active",
        seoTitle: "5kVA 48V Hybrid Solar Inverter Price Nigeria Super Home | Linos Security",
        seoDesc: "Get the SUPER HOME PREMIUM 5kVA 48V Hybrid Solar Inverter in Nigeria. Power your entire home, including ACs and pumps. High-capacity, durable, with pro installation.",
        category: "Solar Power",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Super%20Home%205kva%20Hybrid%20Solar%20Inverter%20Pack"
    },
    {
        handle: "classic-business-7-5kva-48v-hybrid-inverter",
        title: "CLASSIC BUSINESS PREMIUM INSTALLATION 7.5kva 48v Hybride Solar Inverter",
        body: "<p>A robust commercial-grade system. This 7.5kVA 48V hybrid inverter is designed for small businesses, providing reliable power for multiple AC units, fridges, and office equipment, ensuring your operations never stop.</p>",
        price: 6899999.99,
        image: "https://i.postimg.cc/5ygPbQGJ/15kva-setup.jpg",
        status: "active",
        seoTitle: "7.5kVA 48V Hybrid Solar Inverter Price Nigeria Business | Linos Security",
        seoDesc: "Buy the CLASSIC BUSINESS 7.5kVA 48V Hybrid Solar Inverter in Nigeria. Perfect for small businesses to keep ACs and equipment running. Durable & efficient. Order now!",
        category: "Solar Power",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Classic%20Business%207.5kva%20Hybrid%20Solar%20Inverter"
    },
    {
        handle: "super-business-10kva-48v-hybrid-inverter",
        title: "SUPER BUSINESS POWER PACK 10kva 48v Hybride Solar Inverter",
        body: "<p>High-capacity power for large businesses. This 10kVA 48V hybrid system is engineered to handle heavy commercial loads, including multiple ACs, pumps, and industrial equipment, delivering non-stop, efficient performance.</p>",
        price: 8499000,
        image: "https://i.postimg.cc/m2FRZbjL/Cworth-batteries.jpg",
        status: "active",
        seoTitle: "10kVA 48V Hybrid Solar Inverter Price Nigeria Super Business | Linos Security",
        seoDesc: "Get the SUPER BUSINESS 10kVA 48V Hybrid Solar Inverter in Nigeria. High-capacity solution for large businesses to ensure non-stop operations. Durable and efficient. Order today!",
        category: "Solar Power",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Super%20Business%2010kva%20Hybrid%20Solar%20Inverter"
    },
    {
        handle: "d10-turbo-smart-gate-opener",
        title: "Remote Controlled gates D10 Turbo SMΔRT",
        body: "<p>The D10 Turbo SMΔRT gate opener combines unrivalled speed (43m/min) with smart control for residential gates up to 250kg. It features a high 1500-cycle life and storage for multiple remotes, offering the pinnacle of convenience and safety.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/763Hgbcn/d3-smart-gate-machine.jpg",
        status: "active",
        seoTitle: "D10 Turbo SMΔRT Gate Opener Price Nigeria | Linos Security",
        seoDesc: "Buy the D10 Turbo SMΔRT remote-controlled gate opener in Nigeria. High-speed, durable with 1500-cycle life, ideal for residential gates up to 250kg. Get a quote today!",
        category: "Gate Automation",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20the%20D10%20Turbo%20SMART%20Remote%20Controlled%20Gate"
    },
    {
        handle: "fixed-security-bollards",
        title: "Bollard Security system",
        body: "<p>Fixed security bollards are permanent, high-strength steel structures designed to prevent vehicle ramming attacks and protect pedestrians, storefronts, and critical infrastructure. A durable, low-maintenance security solution.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/3wXHQmS1/bollards.jpg",
        status: "active",
        seoTitle: "Fixed Security Bollards Price Nigeria Installation | Linos Security",
        seoDesc: "Install high-security fixed bollards in Nigeria to prevent vehicle attacks and protect premises. Durable steel construction for ultimate perimeter security. Get a quote.",
        category: "Vehicle Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20the%20Bollard%20Security%20System"
    },
    {
        handle: "body-security-scanners",
        title: "Body security Scanners",
        body: "<p>Advanced body scanners for enhanced security screening. Ideal for high-security environments like corporate HQs, airports, and events, they provide non-intrusive detection of metallic and non-metallic threats.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/cJnfx4wP/face-n-finger.jpg",
        status: "active",
        seoTitle: "Body Scanners for Security Price Nigeria | Linos Security",
        seoDesc: "Buy advanced body scanners for security screening in Nigeria. Ideal for corporate, government, and event security. Non-intrusive threat detection. Get a quote today!",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20a%20Body%20Security%20Scanner"
    },
    {
        handle: "hikvision-ds-k1t804amf-terminal",
        title: "Hikvision DS-K1T804AMF(O-STD)",
        body: "<p>A versatile multi-functional terminal for access control and time attendance. Features include fingerprint recognition, card reading, face detection, and an integrated camera, all on a touchscreen display.</p>",
        price: 120000,
        image: "https://i.postimg.cc/cJnfx4wP/face-n-finger.jpg",
        status: "active",
        seoTitle: "Hikvision DS-K1T804AMF Multifunctional Terminal Price Nigeria | Linos Security",
        seoDesc: "Buy the Hikvision DS-K1T804AMF(O-STD) in Nigeria. A multifunctional terminal with fingerprint, card, and face recognition for access control and attendance. Order now!",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Hikvision%20DS-K1T804AMF%20Access%20Terminal"
    },
    {
        handle: "hikvision-ds-k2804-panel",
        title: "Access Control Panel DS-K2804",
        body: "<p>A robust access control panel for managing security in commercial and residential buildings. It seamlessly integrates with card readers, biometric scanners, and door hardware for centralized entry control.</p>",
        price: 123000,
        image: "https://i.postimg.cc/kX3zqB8X/face-recognition.jpg",
        status: "active",
        seoTitle: "Hikvision DS-K2804 Access Control Panel Price Nigeria | Linos Security",
        seoDesc: "Buy the Hikvision DS-K2804 Access Control Panel in Nigeria. Centralized management for card readers and biometrics. Reliable and secure for any facility. Order now!",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20DS-K2804%20Access%20Control%20Panel"
    },
    {
        handle: "zkteco-vf780-face-palm-reader",
        title: "Face and Palm Recognition Reader -VF780 Zkteco",
        body: "<p>A cutting-edge biometric terminal offering both face and palm recognition. It provides high-speed, accurate, and contactless multi-modal authentication for maximum security and hygiene.</p>",
        price: 116400,
        image: "https://i.postimg.cc/cJnfx4wP/face-n-finger.jpg",
        status: "active",
        seoTitle: "ZKTeco VF780 Face Palm Reader Price Nigeria | Linos Security",
        seoDesc: "Buy the ZKTeco VF780 Face and Palm Recognition Reader in Nigeria. High-speed, contactless biometric authentication for access control. Secure and hygienic. Order now!",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20ZKTeco%20VF780%20Face%20and%20Palm%20Reader"
    },
    {
        handle: "zkteco-f7c-fingerprint-reader",
        title: "Zkteco F7-C Fingerprint/Card/Password Access Control",
        body: "<p>A highly reliable fingerprint reader for access control and time attendance. It features multiple authentication methods (fingerprint, card, password), durable construction, and a user-friendly interface.</p>",
        price: 103800,
        image: "https://i.postimg.cc/bvWLgB98/finger-print.jpg",
        status: "active",
        seoTitle: "ZKTeco F7-C Fingerprint Reader Price Nigeria | Linos Security",
        seoDesc: "Buy the ZKTeco F7-C Fingerprint Access Control Reader in Nigeria. Durable and reliable with card, fingerprint, and password options. Perfect for any door. Order now!",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20ZKTeco%20F7-C%20Fingerprint%20Reader"
    },
    {
        handle: "hikvision-ds-k1t343mf-terminal",
        title: "Face Recognition Access Control DS-K1T343MF",
        body: "<p>An advanced face recognition terminal for high-security applications. It combines facial recognition with multi-modal authentication and a wide dynamic range (WDR) camera for accurate performance in various lighting.</p>",
        price: 153600,
        image: "https://i.postimg.cc/kX3zqB8X/face-recognition.jpg",
        status: "active",
        seoTitle: "Hikvision DS-K1T343MF Face Recognition Reader Price Nigeria | Linos Security",
        seoDesc: "Buy the Hikvision DS-K1T343MF Face Recognition Access Control in Nigeria. High-security terminal with WDR camera and multi-modal authentication. Perfect for restricted areas.",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Hikvision%20DS-K1T343MF%20Face%20Recognition%20Terminal"
    },
    {
        handle: "full-height-turnstile-gate",
        title: "Full Height Turnstile Gate",
        body: "<p>Full-height turnstiles, often called \"rotogo,\" provide a high-security, physical barrier that prevents unauthorized access like tailgating. They are robust, durable, and ideal for perimeter fencing and high-traffic areas.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/T2zM1tzS/full-height-turnstile.jpg",
        status: "active",
        seoTitle: "Full Height Turnstile Gate Price Nigeria Installation | Linos Security",
        seoDesc: "Install full-height turnstile gates in Nigeria for high-security entry control. Prevents tailgating, durable construction, ideal for factories and stadiums. Get a quote.",
        category: "Gate Automation",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20a%20Full%20Height%20Turnstile%20Gate"
    },
    {
        handle: "swing-turnstiles",
        title: "Swing Turnstiles",
        body: "<p>Modern and aesthetic swing turnstiles provide secure, lane-style pedestrian access control. They offer a sleek look with safety features, making them ideal for corporate lobbies, airports, and gyms.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/CLqP2YQV/swing-turnstile.jpg",
        status: "active",
        seoTitle: "Swing Turnstile Gate Price Nigeria | Linos Security",
        seoDesc: "Buy elegant swing turnstiles in Nigeria for secure pedestrian flow management. Ideal for corporate lobbies and airports. Aesthetic design with advanced safety. Get a quote.",
        category: "Gate Automation",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20Swing%20Turnstiles"
    },
    {
        handle: "estate-management-security-solution",
        title: "Estate Management Solution",
        body: "<p>A comprehensive security solution for estates. It restricts unauthorized entry, integrates with CCTV, automates resident access via RFID/remotes, simplifies visitor management, and collects data for efficient, safe community management.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/85JVkD3W/lin-os-men-on-duty.png",
        status: "active",
        seoTitle: "Estate Management Security Solution Price Nigeria | Linos Security",
        seoDesc: "Get a complete Estate Management Security Solution in Nigeria. Control access, manage visitors, integrate CCTV, and ensure a safe community environment. Get a quote today.",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20the%20Estate%20Management%20Solution"
    },
    {
        handle: "centurion-barrier-sector-ii",
        title: "Centurion Barrier Sector II",
        body: "<p>A heavy-duty vehicle barrier gate designed for high-traffic commercial and industrial applications. It offers reliable and fast operation for access control points.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/CLqP2YQV/swing-turnstile.jpg",
        status: "active",
        seoTitle: "Centurion Barrier Sector II Price Nigeria | Linos Security",
        seoDesc: "Buy the Centurion Barrier Sector II heavy-duty gate in Nigeria. Reliable and fast operation for high-traffic commercial and industrial access points. Get a quote.",
        category: "Gate Automation",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20the%20Centurion%20Barrier%20Sector%20II"
    },
    {
        handle: "retractable-bollards",
        title: "Retractable Bollard",
        body: "<p>Automatic or manually operated bollards that retract into the ground to allow vehicle passage, providing flexible security. Ideal for driveways, loading bays, and areas requiring occasional access control.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/HnBYDXx7/retractable-bollard.jpg",
        status: "active",
        seoTitle: "Retractable Bollard Price Nigeria | Linos Security",
        seoDesc: "Install retractable bollards in Nigeria for flexible vehicle access control. Automatic or manual operation, durable construction. Perfect for driveways and loading bays. Get a quote.",
        category: "Vehicle Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20Retractable%20Bollards"
    },
    {
        handle: "tyre-security-spikes",
        title: "Tyre Security Spikes",
        body: "<p>A directional traffic control device that automatically retracts to allow authorized vehicles to pass but punctures tires of vehicles attempting to go the wrong way or enter without authorization.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/8cDcVTmr/tyre-killer.jpg",
        status: "active",
        seoTitle: "Tyre Security Spikes Price Nigeria | Linos Security",
        seoDesc: "Buy Tyre Security Spikes (Tire Killers) in Nigeria for directional traffic control. Automatic retraction, weather-resistant, and a strong visual deterrent. Get a quote.",
        category: "Vehicle Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20Tyre%20Security%20Spikes"
    },
    {
        handle: "v380-standalone-wifi-camera",
        title: "Standalone Wifi Camera & Installation – v380",
        body: "<p>A cost-effective, single-channel Wi-Fi CCTV system starting at ₦30,000. Perfect for shops, offices, and homes, this V380 camera lets you monitor your property, kids, or staff remotely via your mobile phone using an internet service like MTN.</p>",
        price: 105000,
        image: "https://i.postimg.cc/nrbRBh7H/G3-Hikvision-4k-8mp-Ip-Camera-Colorvu-Ds-2cd2387g3-li2uy-Acusense-3-0-Dual-Mic.jpg",
        status: "active",
        seoTitle: "V380 Standalone WiFi Camera Price Nigeria Installation | Linos Security",
        seoDesc: "Buy a Standalone V380 Wi-Fi Camera & Installation in Nigeria starting at ₦30k. Ideal for shops and homes. Remote monitoring via mobile phone. Order now!",
        category: "CCTV",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Standalone%20Wifi%20Camera%20Installation"
    },
    {
        handle: "v380-triple-lens-4g-solar-camera",
        title: "Triple Lens 4G Solar Camera – v380",
        body: "<p>An advanced 4G solar-powered PTZ camera with three lenses for a triple-screen preview. It features 12MP resolution, full-color night vision, human tracking, face recognition, and two-way audio. No Wi-Fi needed.</p>",
        price: 130000,
        image: "https://i.postimg.cc/B6F46Rnm/dual-lens.jpg",
        status: "active",
        seoTitle: "V380 Triple Lens 4G Solar Camera Price Nigeria | Linos Security",
        seoDesc: "Buy the V380 Triple Lens 4G Solar PTZ Camera in Nigeria. 12MP, human tracking, color night vision, no Wi-Fi needed. Perfect for remote monitoring. Order now!",
        category: "CCTV",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Triple%20Lens%204G%20Solar%20Camera"
    },
    {
        handle: "v380-dual-lens-4g-solar-ptz",
        title: "Dual Lens 4G Solar PTZ Camera – v380",
        body: "<p>A powerful dual-lens 4G solar PTZ camera that provides comprehensive surveillance with pan, tilt, and zoom functions. Ideal for large outdoor areas without reliable Wi-Fi.</p>",
        price: 120000,
        image: "https://i.postimg.cc/B6F46Rnm/dual-lens.jpg",
        status: "active",
        seoTitle: "V380 Dual Lens 4G Solar PTZ Camera Price Nigeria | Linos Security",
        seoDesc: "Buy the V380 Dual Lens 4G Solar PTZ Camera in Nigeria. Pan, tilt, zoom, and color night vision. No Wi-Fi needed for remote areas. Order now!",
        category: "CCTV",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20order%20the%20Dual%20Lens%204G%20Solar%20PTZ%20Camera"
    },
    {
        handle: "basic-8ch-cctv-system",
        title: "Basic 8 Channels CCTV System Plus Installation",
        body: "<p>A complete 8-channel security system with 8 cameras and an 8-channel DVR. This package includes everything for a comprehensive home or office CCTV setup, with prices starting at ₦320,000 depending on site specifics.</p>",
        price: 420000,
        image: "https://i.postimg.cc/L69FKJL3/droplets-cctv-installaton-in-port-harcourt-ip-cameras-hikvision-cameras-8-channel-CCTV-system-plus-i.jpg",
        status: "active",
        seoTitle: "8 Channel CCTV System Price Nigeria Installation | Linos Security",
        seoDesc: "Buy a Basic 8 Channel CCTV System with Installation in Nigeria. Complete package with 8 cameras and DVR for comprehensive property surveillance. Order now!",
        category: "CCTV",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20the%20Basic%208%20Channel%20CCTV%20System"
    },
    {
        handle: "code-3-lightbar",
        title: "Code 3 lightbar for security car",
        body: "<p>High-visibility LED light bar for security vehicles. Ensures your patrol cars are seen, providing effective warning and presence during security operations.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/L8659F8M/Gemini-Generated-Image-ra0ilkra0ilkra0i.png",
        status: "active",
        seoTitle: "Code 3 Lightbar for Security Cars Price Nigeria | Linos Security",
        seoDesc: "Buy Code 3 lightbars for security cars in Nigeria. High-visibility LED warning lights for patrol vehicles. Durable and effective. Get a quote today.",
        category: "Security Accessories",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20a%20Code%203%20lightbar"
    },
    {
        handle: "xray-baggage-scanner",
        title: "Xray Baggage scanners",
        body: "<p>High-performance X-ray baggage scanners for screening luggage, bags, and parcels. Essential for security at corporate buildings, airports, malls, and events to detect prohibited items.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/ZnK29HB4/Astrophysics-X-Ray-Baggage-Scanner-XIS-100XDX.jpg",
        status: "active",
        seoTitle: "Xray Baggage Scanner Price Nigeria | Linos Security",
        seoDesc: "Buy X-ray Baggage Scanners in Nigeria for high-throughput security screening. Detect threats in luggage and parcels. Ideal for corporate and public venues. Get a quote.",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20an%20Xray%20Baggage%20Scanner"
    },
    {
        handle: "portable-safe-box",
        title: "portable Safe",
        body: "<p>A secure and durable portable safe box for protecting valuables, documents, and cash. Ideal for home, office, or hotel use, offering peace of mind.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/SNCHtn6g/Gemini-Generated-Image-6ps8a36ps8a36ps8.png",
        status: "active",
        seoTitle: "Portable Safe Box Price Nigeria | Linos Security",
        seoDesc: "Buy a portable safe box in Nigeria. Durable and secure for protecting cash, documents, and valuables at home or in the office. Get a quote today.",
        category: "Vehicle Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20a%20Portable%20Safe"
    },
    {
        handle: "smart-access-control-door-locks",
        title: "Access control Smart Door locks",
        body: "<p>Advanced keyless entry systems combining access control panels with smart locking mechanisms. Ideal for commercial and high-security residential applications, offering centralized management and audit trails.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/Hk19WNgK/Access-Control-Installation-Los-Angeles.jpg",
        status: "active",
        seoTitle: "Smart Access Control Door Locks Price Nigeria | Linos Security",
        seoDesc: "Buy smart access control door locks in Nigeria. Ideal for commercial security with centralized management and keyless entry. Get a quote for installation today.",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20Access%20Control%20Smart%20Door%20Locks"
    },
    {
        handle: "smart-home-keyless-door-lock",
        title: "Smart Home keyless door lock",
        body: "<p>Modern, user-friendly keyless door locks for homes. Offer convenience with multiple access methods like fingerprint, PIN code, and smartphone app control, perfect for families and Airbnb rentals.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/HLsZHN0b/Best-smart-lock-for-a-keyless-home.gif",
        status: "active",
        seoTitle: "Smart Home Keyless Door Lock Price Nigeria | Linos Security",
        seoDesc: "Upgrade to a Smart Home Keyless Door Lock in Nigeria. Fingerprint, PIN, and app access for ultimate convenience and family safety. Get a quote today.",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20a%20Smart%20Home%20Keyless%20Door%20Lock"
    },
    {
        handle: "smart-solar-sliding-gate-motor",
        title: "Smart solar remote control sliding gate machine",
        body: "<p>An efficient, solar-powered sliding gate motor. Perfect for locations with unreliable electricity, offering eco-friendly, remote-controlled access for residential and commercial gates.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/3x39Cqcs/Centsys-Centurion-D5-EVO-Smart-Solar-Automatic-Slide-Gate-Motor-4m-Racking.jpg",
        status: "active",
        seoTitle: "Solar Sliding Gate Motor Price Nigeria | Linos Security",
        seoDesc: "Buy a Smart Solar Remote Control Sliding Gate Machine in Nigeria. Eco-friendly, off-grid gate automation for reliable access control. Get a quote today.",
        category: "Gate Automation",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20the%20Smart%20Solar%20Sliding%20Gate%20Motor"
    },
    {
        handle: "digital-door-lock",
        title: "Digital Door lock",
        body: "<p>A sleek and modern digital door lock offering keyless convenience. Typically features keypad entry, making it a simple upgrade for enhanced home security without complex wiring.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/8cBM7pND/Digital-door-lock.jpg",
        status: "active",
        seoTitle: "Digital Door Lock Price Nigeria | Linos Security",
        seoDesc: "Buy a Digital Door Lock in Nigeria for easy, keyless entry. Sleek design with PIN code access for enhanced home security. Get a quote today.",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20a%20Digital%20Door%20Lock"
    },
    {
        handle: "smart-matt-black-door-lock",
        title: "Smart matt black Door locks",
        body: "<p>Stylish and secure smart locks finished in premium matt black. They combine high-end aesthetics with advanced features like fingerprint, code, and RFID access, perfect for modern interiors.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/90Vq56Tk/Serrure-De-Porte-Intelligente-Smart-Lock-Door-Battery-Last-Kaadas-Smart-Lock-For-Glass-Door-Buy-Ka.jpg",
        status: "active",
        seoTitle: "Matt Black Smart Door Lock Price Nigeria | Linos Security",
        seoDesc: "Buy Smart Matt Black Door Locks in Nigeria. Premium finish with fingerprint, code, and RFID access. Stylish security for modern homes. Get a quote.",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20a%20Smart%20Matt%20Black%20Door%20Lock"
    },
    {
        handle: "smart-glass-door-lock",
        title: "Smart glass Door Lock",
        body: "<p>Specialized electronic locks designed for glass doors (sliding or swing) in offices and commercial spaces. They provide secure access control while maintaining a professional, modern look.</p>",
        price: "Get Quote",
        image: "https://i.postimg.cc/tTdY5Bfd/Smart-Glass-Door-Biometric-Fingerprint-Lock-RFID-IC-Card-Code-Office-Electric-Lock-Sliding-Door-Eas.jpg",
        status: "active",
        seoTitle: "Smart Glass Door Lock Price Nigeria | Linos Security",
        seoDesc: "Buy Smart Glass Door Locks in Nigeria for offices. Biometric, RFID, and code access for sliding or swing glass doors. Secure and professional. Get a quote.",
        category: "Access Control",
        whatsapp: "https://wa.me/2348069423078?text=Hello%20Linos,%20I%20want%20to%20get%20a%20quote%20for%20a%20Smart%20Glass%20Door%20Lock"
    }
];

const finalProducts = productsRaw.map(p => ({
    name: p.title,
    slug: p.handle,
    category: p.category,
    price: p.price,
    image: p.image || 'https://i.postimg.cc/QdTMzQvh/5kva_setup.jpg',
    description: p.body.replace(/<[^>]*>?/gm, '').trim(),
    body_html: p.body,
    seo: {
        meta_title: p.seoTitle,
        meta_description: p.seoDesc
    },
    whatsapp: p.whatsapp
}));

const data = {
    store: "Linos E Security Ltd",
    currency: "NGN",
    products: finalProducts
};

console.log(JSON.stringify(data, null, 4));
